project:
  type: website
  output-dir: docs
  
website:
  site-url: https://nanoyan.github.io/quarto-prototyp/
  title: "quarto-prototyp"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/nanoyan/quarto-prototyp/
  repo-actions: [issue]
  navbar:
    logo: IQB-klein.png
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
      - text: External site
        href: https://iqb-vocabs.github.io/p80/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
